

#define PIECE_MAP_PAWN_0 0x0
#define PIECE_MAP_PAWN_1 0x1
#define PIECE_MAP_PAWN_2 0x2
#define PIECE_MAP_PAWN_3 0x3
#define PIECE_MAP_PAWN_4 0x4
#define PIECE_MAP_PAWN_5 0x5
#define PIECE_MAP_PAWN_6 0x6
#define PIECE_MAP_PAWN_7 0x7
#define PIECE_MAP_KNIGHT_0 0x8
#define PIECE_MAP_KNIGHT_1 0x9
#define PIECE_MAP_BISHOP_0 0xa
#define PIECE_MAP_BISHOP_1 0xb
#define PIECE_MAP_ROOK_0 0xc
#define PIECE_MAP_ROOK_1 0xd
#define PIECE_MAP_KING 0xe
#define PIECE_MAP_QUEEN 0xf
