#pragma once

// See https://en.wikipedia.org/wiki/Rules_of_chess#End_of_the_game for details.
enum Termination {
	TERMINATION_CHECKMATE,
	TERMINATION_STALEMATE,
	TERMINATION_RESIGN,
	TERMINATION_TIME,
	TERMINATION_NO_CAPTURE,
	TERMINATION_REPETITION,
	TERMINATION_INSUFFICIENT_MATERIAL,
	TERMINATION_DRAW_BY_AGREEMENT,
	TERMINATION_OTHER,
	TERMINATION_NONE,
};
