/* SPDX-License-Identifier: GPL-3.0-only */

#ifndef ZULOID_SWITCHES_H
#define ZULOID_SWITCHES_H

#define ZULOID_ENABLE_OPENMP 1
#define ZULOID_ENABLE_DEBUG_MESSAGES 1
#define ZULOID_ENABLE_SHOW_PID 1

#endif
